import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full`}>
        <main className="mx-auto mt-10 flex w-full flex-col items-center gap-10 p-4">
          <h1
            className="w-max bg-gradient-to-r from-pink-600 via-purple-600 to-fuchsia-600 
						bg-clip-text text-3xl font-extrabold text-transparent md:text-5xl lg:text-6xl"
          >
            Tic-Tac-Toe
          </h1>
          {children}
        </main>
      </body>
    </html>
  );
}
